name: autozone
description: Proyecto Final - Gestión de Vehículos - ITLA 2026
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP y almacenamiento
  http: ^1.2.0
  shared_preferences: ^2.2.2

  # Cámara y galería
  image_picker: ^1.1.2

  # Imágenes de red con caché
  cached_network_image: ^3.3.1

  # Gestión de estado
  provider: ^6.1.2

  # Abrir links, teléfono, correo
  url_launcher: ^6.3.0

  # Icono de la app (se configura luego)
  flutter_launcher_icons: ^0.14.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true